### ISSUE TITLE
tier4_simulator_launch_param_path is conflicting a file path

### ISSUE THREAD

**Issue by Yukio247** [tier4/autoware.universe#182]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

An environment variable name `tier4_simulator_launch_param_path`is defined [HERE](https://github.com/tier4/autoware.universe/blob/tier4/main/launch/tier4_simulator_launch/launch/simulator.launch.xml#L2).
And the name is used in [HERE](https://github.com/tier4/autoware.universe/blob/tier4/main/launch/tier4_simulator_launch/launch/simulator.launch.xml#L23). You can see the `config` directory is conflicting.
When I tried to use fault injection in the scenario simulator, I could not use the fault injection because of duplicate "config" directories.

### Expected behavior

I can use Fault Injection in the scenario simulator.

### Actual behavior

I cannot use Fault Injection in the scenario simulator.

### Steps to reproduce

1. Run scenario simulator.
2. Publish a something fault injection.

**Comment by kminoda** [comment]
Thank you for reporting, and sorry for my possible mistake. I did not test this modification on scenario simulator since it was a simple change.
I opened a PR to fix this issue: https://github.com/autowarefoundation/autoware.universe/pull/2281

**Comment by shmpwk** [comment]
Maybe we should change this also?
https://github.com/tier4/autoware_launch/blob/awf-latest/simulator_launch/launch/simulator.launch.xml#L18

**Comment by shmpwk** [comment]
https://github.com/autowarefoundation/autoware.universe/pull/2281 will be merged into tier4/main branch in this repos by https://github.com/tier4/autoware.universe/pull/181.
